CREATE TABLE IF NOT EXISTS MPAA_rating (
    rating_id integer references films(rating_id),
    name varchar(100),
    PRIMARY KEY (rating)
    );

CREATE TABLE IF NOT EXISTS genre (
    genre_id integer generated by default as identity primary key,
    name varchar(100) NOT NULL
    );

CREATE TABLE IF NOT EXISTS films (
    film_id long generated by default as identity primary key,
    name varchar(100),
    description varchar(255),
    duration long,
    release_date date,
    rating_id integer references MPAA_rating (rating_id)
    );

CREATE TABLE IF NOT EXISTS film_genre (
    film_id long references films (film_id),
    genre_id integer references genre (genre_id)
    );

CREATE TABLE IF NOT EXISTS users (
    user_id long generated by default as identity primary key,
    name varchar(100),
    login varchar(100) UNIQUE,
    email varchar(100) UNIQUE,
    birthday date
    );

CREATE TABLE IF NOT EXISTS friends (
    user_id long references users (user_id),
    friend_id long references users (user_id),
    accepted boolean,
    PRIMARY KEY (user_id, friend_id)
    );

CREATE TABLE IF NOT EXISTS likes (
    film_id long references films (film_id),
    user_id long references users (user_id),
    PRIMARY KEY (film_id, user_id)
);
