CREATE TABLE IF NOT EXISTS mpa
(
    rating_id integer generated by default as identity primary key,
    name varchar(100)
);

CREATE TABLE IF NOT EXISTS genre
(
    genre_id integer generated by default as identity primary key,
    name varchar(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS films
(
    film_id bigint generated by default as identity(START WITH 1) primary key,
    name varchar(100),
    description varchar(255),
    duration bigint,
    release_date date,
    rating_id integer references mpa (rating_id)
);

CREATE TABLE IF NOT EXISTS users
(
    user_id bigint generated by default as identity(START WITH 1) primary key,
    name varchar(100),
    login varchar(100) UNIQUE,
    email varchar(100) UNIQUE,
    birthday date
);


CREATE TABLE IF NOT EXISTS film_genre
(
    film_id bigint references films (film_id),
    genre_id integer references genre (genre_id)
);

CREATE TABLE IF NOT EXISTS friends
(
    user_id bigint references users (user_id),
    friend_id bigint references users (user_id),
    PRIMARY KEY (user_id, friend_id)
);

CREATE TABLE IF NOT EXISTS likes
(
    film_id bigint references films (film_id),
    user_id bigint references users (user_id),
    PRIMARY KEY (film_id, user_id)
);
